"""Storage backend protocol definition."""

from __future__ import annotations

from typing import Protocol

from models.client import Client
from models.consent import Consent
from models.saml import SAMLIdPConfig
from models.scope import Scope
from models.token import AuthorizationCode, DeviceCode, RefreshToken, TokenRevocationEntry
from models.user import SocialAccount, User


class StorageBackend(Protocol):
    """Abstract storage backend protocol.

    All methods are async to support both local and cloud backends.
    """

    # User operations
    async def get_user(self, user_id: str) -> User | None: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def create_user(self, user: User) -> User: ...
    async def update_user(self, user: User) -> User: ...
    async def list_users(self, page: int = 1, page_size: int = 20) -> tuple[list[User], int]: ...
    async def search_users(self, query: str, page: int = 1, page_size: int = 20) -> tuple[list[User], int]: ...

    # Social account operations
    async def get_social_account(self, provider: str, provider_user_id: str) -> SocialAccount | None: ...
    async def get_social_accounts_for_user(self, user_id: str) -> list[SocialAccount]: ...
    async def create_social_account(self, account: SocialAccount) -> SocialAccount: ...

    # Client operations
    async def get_client(self, client_id: str) -> Client | None: ...
    async def get_client_by_name(self, name: str) -> Client | None: ...
    async def create_client(self, client: Client) -> Client: ...
    async def update_client(self, client: Client) -> Client: ...
    async def list_clients(self, page: int = 1, page_size: int = 20) -> tuple[list[Client], int]: ...

    # Authorization code operations
    async def store_auth_code(self, code: AuthorizationCode) -> None: ...
    async def get_auth_code(self, code_hash: str) -> AuthorizationCode | None: ...
    async def mark_auth_code_used(self, code_hash: str) -> None: ...

    # Refresh token operations
    async def store_refresh_token(self, token: RefreshToken) -> None: ...
    async def get_refresh_token(self, token_hash: str) -> RefreshToken | None: ...
    async def mark_refresh_token_used(self, token_hash: str) -> None: ...
    async def revoke_refresh_token(self, token_hash: str) -> None: ...
    async def revoke_token_family(self, family_id: str) -> None: ...
    async def revoke_tokens_for_client(self, client_id: str) -> None: ...
    async def revoke_tokens_for_user_client(self, user_id: str, client_id: str) -> None: ...
    async def get_refresh_tokens_by_family(self, family_id: str) -> list[RefreshToken]: ...

    # Token revocation entries (for access tokens)
    async def store_revocation(self, entry: TokenRevocationEntry) -> None: ...
    async def is_token_revoked(self, jti: str) -> bool: ...

    # Consent operations
    async def get_consent(self, consent_id: str) -> Consent | None: ...
    async def get_active_consent(self, user_id: str, client_id: str) -> Consent | None: ...
    async def get_consents_for_user(self, user_id: str) -> list[Consent]: ...
    async def create_consent(self, consent: Consent) -> Consent: ...
    async def revoke_consent(self, consent_id: str) -> None: ...

    # Device code operations
    async def store_device_code(self, device_code: DeviceCode) -> None: ...
    async def get_device_code(self, device_code_hash: str) -> DeviceCode | None: ...
    async def get_device_code_by_user_code(self, user_code: str) -> DeviceCode | None: ...
    async def update_device_code(self, device_code: DeviceCode) -> None: ...

    # Scope operations
    async def get_scope(self, name: str) -> Scope | None: ...
    async def list_scopes(self) -> list[Scope]: ...
    async def create_scope(self, scope: Scope) -> Scope: ...
    async def delete_scope(self, name: str) -> None: ...

    # SAML IdP operations
    async def get_saml_idps(self) -> list[SAMLIdPConfig]: ...
    async def get_saml_idp(self, idp_id: str) -> SAMLIdPConfig | None: ...
    async def create_saml_idp(self, idp: SAMLIdPConfig) -> SAMLIdPConfig: ...

    # Health check
    async def health_check(self) -> bool: ...

    # Initialization
    async def initialize(self) -> None: ...
